vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        trick_images:
            uri_prefix: '%trick_images%'
            upload_destination: '%kernel.project_dir%/public/%trick_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
