@startuml Cas_d_utilisation_user
scale 1
Left to right direction
skinparam packageStyle rect
actor user

rectangle utilisation_user{
(user) -- (ajouter une figure)
(user) -- (Consulter une figure)
(user) -- (Consulter la liste des figure)
(user) -- (ajouter un commentaire)
(user) -- (modifier/supprimer un commentaire)
(user) -- (modifier/supprimer une figure)

(modifier/supprimer une figure) ..> (Qui lui appartient) :include

(modifier/supprimer une figure) ..> (authentification) :include
(ajouter une figure) ..> (authentification) :include
(ajouter un commentaire) ..> (authentification) :include
(modifier/supprimer un commentaire) ..> (authentification) :include
(modifier/supprimer un commentaire) ..> (Qui lui appartient) :include

(authentification) ..> (créer un compte) :extend

}
@enduml

